config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :comments, only: [:new, :create, :destroy] do
    collection do
      match :list_comments, via: [:get, :post]
      get :reply_comments
    end
  end

  resources :posts
  resources :profiles

  root to: 'posts#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :parent, class_name: 'Comment'
  belongs_to :post
  belongs_to :user

  before_destroy :destroy_children

  def has_child?
    Comment.count( conditions: { parent_id: id } ) > 0
  end

  def destroy_children
    Comment.where(parent_id: id).destroy_all
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many   :comments, dependent: :destroy

  def prepare_and_save_new_post(current_user)
    self.user = current_user
    if save
      return true
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many   :posts
  has_many   :comments

  has_attached_file :avatar,
    medium: {
      geometry: "30x30#",
      format: :png,
      paperclip_optimizer: {
        gifsicle: false,
        pngquant: false,
        jhead: false,
        jpegoptim: false,
        svgo: false,
        pngout: {strategy: 0},
        advpng: {level: 4},
        optipng: {level: 7},
        pngcrush: {chunks: 'alla'}
      }
    },
  path: "public/system/users/:id/avatars/:style.:extension",
  url: "/system/users/:id/avatars/:style.:extension",
  default_url: "/images/userpic-default.png"

  validates_attachment_content_type :avatar, :content_type => %w(image/jpeg image/jpg image/png)

  def role_symbols#Используется в declarative_authorization
    roles = role.split(',')
    roles.map do |role|
      role.to_sym
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_current_user

  def calc_page page, per_page, count
    if page.to_i * per_page.to_i > count
      (count.to_f / per_page.to_i).ceil
    else
      page
    end
  end

  protected
    def set_current_user
      Authorization.current_user = current_user
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  filter_access_to
  before_action :load_comment, only: [:edit, :reply_comments, :destroy]

  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @post = @comment.post
    @comment.save
  end

  def destroy
    @post = @comment.post
    @comment.destroy
  end

  def list_comments
    all_comments = Post.find(params[:post_id]).comments.includes(:user)
    @comments = all_comments.group_by(&:parent_id)
    render layout: false
  end

  def reply_comments
    @post = @comment.post
    render layout: false
  end

  private
    def load_comment
      @comment = Comment.find_by_id params[:id]
    end

    def comment_params
      params.require(:comment).permit(:body, :post_id, :parent_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  filter_access_to
  before_action :find_resource!, only: [:show, :edit, :destroy, :create,
                                        :update]
  before_action :build_resource, only: [:new, :create]

  def index
    @posts = Post.all.includes(:user).paginate page: calc_page(params[:page], 10, Post.all.count), per_page: 10
  end

  def show
  end

  def new
  end

  def create
    if @post.prepare_and_save_new_post(current_user)
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private 
    def find_resource!
      post_id = params[:id]
      @post = Post.find_by_id(post_id)
    end

    def post_params
      params.require(:post).permit( :title, :body) if params[:post]
    end

    def build_resource
      @post = Post.new(post_params)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  filter_access_to
  before_action :find_user, only: [:show, :edit, :update]

  def show
    @posts = @profile.posts.paginate page: calc_page(params[:page], 10, @profile.posts.count), per_page: 10
  end

  def edit
  end

  def update
    binding.pry
    if @profile.update(profile_params)
      sign_in User, @profile, bypass: true
      redirect_to profile_path
    else
     render :edit
    end 
  end

  private
    def find_user
      @profile = User.find(params[:id])
    end

    def profile_params
      params.require(:user).permit(:email, :password, :password_confirmation, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_user(user, link_class = nil)
    link_to(user.email, profile_url(user), class: link_class)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comments_count post
    post.comments.count
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.haml
%li
  - if user
    = link_to profile_path(user), class: 'userpic', id: comment.id do
      = image_tag(user.avatar.url)
  .box
    - if user
      .info{class: user.id}
        = link_to "#{user.email}","#", class: 'author'
        в #{comment.created_at}
    .comment
      = raw comment.body
    - if current_user
      = link_to "Ответить", "#", class: 'reply', remote: true, id: comment.id
    - permitted_to? :destroy, comment do
      = link_to "Удалить", comment_path(comment), method: :delete, class: 'delete', remote: true, id: comment.id
  %ul
    - (@comments[comment.id] || []).each do |comment|
      = render partial: 'comments/comment', locals: {comment: comment, user: comment.user}

app/views/comments/_form.html.haml
= form_tag Comment.new, url: new_comment_path, remote: true, class: "reply", id: "comment", name: "comment" do
  .comment
    = hidden_field_tag "comment[post_id]", post.id
    = hidden_field_tag "comment[parent_id]", comment.id if comment
    = text_area_tag 'comment[body]',nil, remote: true, id: 'comment', placeholder: "Для отправки нажмите ctrl+Enter, для закрытия формы - Esc"

app/views/comments/_post_comments.html.haml
.comments
  - if current_user
    = render partial: 'comments/form', locals: {post: @post, comment: nil}
  - else
    .sign-in-to-comment
      Чтобы оставить комментарий
      = link_to "войдите на сайт", new_user_session_path
      или
      = link_to "зарегистрируйтесь",new_user_registration_path
  %ul.list

app/views/comments/create.js.haml
$('.comments .list').load('/comments/list_comments?post_id=#{@post.id}', function(){ $('html, body').stop().animate({scrollTop: $('#' + #{@comment.id}).offset().top - 25}); click_reply();});

app/views/comments/destroy.js.haml
$('.comments .list').load('/comments/list_comments?post_id=#{@post.id}', function(){ click_reply();});

app/views/comments/list_comments.html.haml
.comments
  - (@comments[nil] || []).each do |comment|
    = render partial: 'comments/comment', locals: {comment: comment, user: comment.user}

app/views/comments/reply_comments.html.haml
= render partial: 'comments/form', locals: {post: @post, comment: @comment}

app/views/layouts/_header.html.haml
%header
  .wrapper
    = link_to root_path, class: 'logo' do
      = image_tag('logo.png', alt: 'Мой блоге')
    - unless current_user
      %ul.auth
        %li.sign-up
          = link_to 'Регистрация', new_user_registration_path
        %li.sign-in
          = link_to 'Вход', new_user_session_path
    - else
      .user
        .hello Привет, #{link_to current_user.email, profile_path(current_user)}!
        = link_to 'Выход', destroy_user_session_path, method: :delete, class: 'sign-out'
        .actions
          = link_to 'Настройки', edit_profile_path(current_user), class: 'settings'
          - permitted_to? :new, :posts do
            = link_to 'Добавить пост', new_post_path, class: 'add-post'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mysite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body  class='page'>
    <%= render partial: 'layouts/header'%>
    <%= yield %>
</body>
</html>

app/views/posts/_form.html.haml
= form_for @post, html: {class: "fields"} do |f|
  .field.email
    = label_tag :title, 'Заголовок'
    = f.text_field :title, id: :title, placeholder: "Заголовок", class: @post.errors[:title].blank? ? '' : 'error'
  .field.email
    = label_tag :title, 'Текст'
    = f.text_area :body, id: :postContent
  .actions
    = f.submit 'Сохранить изменения', class: "save"

app/views/posts/_short_post.html.haml
%li
  %h2.title
    = link_to raw(post.title), post_path(post)
  .info
    .posted
      %span.m-hidden Опубликовал
      = link_to_user post.user, 'author'
      = post.created_at.strftime("в %H:%M, %d.%m.%Y")
    =# link_to post.comments_count, show_post_path(post) + "#comments", class: "comments #{'active' if !post.comments_count.zero?}", title: 'Перейти к комментариям'
  =# link_to raw(clear_content(post.excerpt)), show_post_path(post), class: 'text'

app/views/posts/edit.html.haml
%article.main
  .wrapper
    %section.content
      .profile-edit
        .page-title РЕАДАКТИРОВАНИЕ ПОСТА
        = render 'form'

app/views/posts/index.html.haml
%article.main
  .wrapper
    %section.content
      %ul.posts
        - @posts.each do |post|
          = render partial: 'short_post', locals: {post: post}
      = will_paginate @post, inner_window: 1

app/views/posts/new.html.haml
%article.main
  .wrapper
    %section.content
      .profile-edit
        .page-title СОЗДАНИЕ ПОСТА
        = render 'form'

app/views/posts/show.html.haml
%article.main
  .wrapper
    %section.content
      .post.v2
        .splash
          .info
            %h1
              = @post.title
            .posted
              Опубликовал
              = link_to_user @post.user
              в #{@post.created_at.strftime("%H:%M, %d.%m.%Y")}
        .controls
          - permitted_to? :edit, @post do
            = link_to 'Редактировать', edit_post_path(@post)
          - permitted_to? :destroy, @post do
            = link_to "Удалить", post_path(@post), method: :delete, data: { confirm: "Уверены?" }
        .text
          = raw @post.body
        = render 'comments/post_comments'
:javascript
  var list = $(".comments .list");

  $.ajax({
    type: "POST",
    url: "/comments/list_comments",
    data: {'post_id': "#{@post.id}"},
    success: function(data) {
      list.html(data);
      key_ctrl_enter();
      click_reply();
    }
  });

app/views/profiles/edit.html.haml
%article.main
  .wrapper
    %section.content
      .profile-edit 
        .page-title РЕАДАКТИРОВАНИЕ ПРОФИЛЯ
        = form_for @profile, url: profile_path(@profile), html: {id: "edit-profile", class: "fields"} do |f|
          .field.userpic
            = f.label :avatar, "Изменить аватар"
            = image_tag @profile.avatar.url, alt: @profile.email, class: "current", height: "60",width: "60"
            = f.file_field :avatar, class: "upload", id: "upload"
            .filename #{ File.basename(@profile.avatar.url(:large)) }
            = link_to "", "#", class: "remove"
          .field.email
            = f.label :email, "Почта"
            = f.text_field :email, id: "email"
          .field.password
            = f.label :password, "Пароль"
            = f.password_field :password, id: "password"
          .field.password-again
            = f.label :password_confirmation, "Еще раз пароль"
            = f.password_field :password_confirmation, id: "password-again"
          .actions
            = f.submit "Сохранить изменения", class: "save"

app/views/profiles/show.html.haml
%article.main
  .wrapper
    %section.content
      .intro ПРОФИЛЬ — #{@profile.email}
      - if @posts.count > 0
        %ul.posts
          - @posts.each do |post|
            = render partial: "posts/short_post", locals: {post: post}
        = will_paginate @posts, inner_window: 1